### PR TITLE
added seeing computation

### PR DESCRIPTION
**Pull request by agb32**

### CODE REVIEW

**Comment by matthewtownson** [comment]
I just realised this function already exists. It can be found in `aotools/turbulence/atmos_conversions.py` and used with `aotools.turbulence.r0_to_seeing()`

**Comment by agb32** [comment]
Yes, but not with L0.
Should I move it into the atmos_conversions.py file?

On Thu, 11 Jan 2018, Matthew Townson wrote:

<I just realised this function already exists. It can be found in `aotools/turbulence/atmos_conversions.py` and used with `aotools.turbulence.r0_to_seeing()`
<
<-- 
<You are receiving this because you authored the thread.
<Reply to this email directly or view it on GitHub:
<https://github.com/AOtools/aotools/pull/34#issuecomment-356979094
<

**Comment by matthewtownson** [comment]
Ah, in that case yes I would update the existing function to include L0.

**Comment by agb32** [comment]
Remind me how I do a merge request...

On Thu, 11 Jan 2018, Matthew Townson wrote:

<Ah, in that case yes I would update the existing function to include L0.
<
<-- 
<You are receiving this because you authored the thread.
<Reply to this email directly or view it on GitHub:
<https://github.com/AOtools/aotools/pull/34#issuecomment-356987174
<

**Comment by agb32** [comment]
No, I think I've done it...

On Thu, 11 Jan 2018, Matthew Townson wrote:

<Ah, in that case yes I would update the existing function to include L0.
<
<-- 
<You are receiving this because you authored the thread.
<Reply to this email directly or view it on GitHub:
<https://github.com/AOtools/aotools/pull/34#issuecomment-356987174
<

**Pull request closed without merging**
